### ISSUE TITLE
Support for multiple windows?

### ISSUE THREAD

**Issue by orschiro** [tsiemens/ChromeTabDeduper#1]
Dear @tsiemens,

Love your extension. Thank you so much!

It's approach to duplicates is something I can really work with well. 

Just one thing. Would it be possible to support multiple windows in the upcoming release?

Eager to hear. :-)

**Comment by tsiemens** [comment]
Hey, good to hear!

Yes, we've got some issues with multi-window right now...

Presumably, yes, we should show all duplicates across all windows.

I'm assuming you're suggesting that we still would want to consider the same tab in multiple windows a duplicate? Or just the same tab in the same window a duplicate? I suppose there could be an option, but which of these would be your preferred use case to start? (I'm not really a multi-window person)

**Comment by orschiro** [comment]
Hey @tsiemens! 

Thanks so much for getting back to me swiftly. :-)

Actually, let me experiment a bit more with my own workflow. 

I discovered the appeal of being in single window mode. 

Maybe I just need to adjust. :-)

Will get back to you with more insights promptly!

**Comment by Cypher1** [comment]
I think it'd be great to have the option (e.g. show tabs in the same window as one colour and tabs in a different windows as another, with the option to disable multi-window mode).

**Comment by tsiemens** [comment]
Sorry this took so long. Was originally waiting for @orschiro to reply with some more details. Then just didn't have time/lost track after @Cypher1 's comment.

This issue should be fixed in 7acf368 , and will be available on the store whenever it gets passed review.
I hope you enjoy the pretty colours!
