### ISSUE TITLE
[Request] Support Firefox?

### ISSUE THREAD

**Issue by FatOrangutan** [tsiemens/ChromeTabDeduper#2]
Firefox supports [webextensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) now and claims that most Chrome extensions should work for it with minimal changes. I tried your add-on with [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) and while the popup worked right away, the options page wasn't available:
![capture](https://user-images.githubusercontent.com/8336638/41755173-8497031a-75f3-11e8-8819-a2a86bc64b41.PNG)

Would be great if you could add support for FF.

**Comment by tsiemens** [comment]
Fascinating! I did not know about this.

I'll see what I can do here, once I've got some down time to make improvements.

In the meantime, I would maybe suggest you try out ~https://addons.mozilla.org/en-US/firefox/addon/tab-deduper/~  https://addons.mozilla.org/en-US/firefox/addon/duplicate-tabs-closer/
This was really the inspiration for me to create a relatively similar version on Chrome. Though it does not support regexes, it is pretty good still.

Edit: I actually did mean the one linked below. My mistake.

**Comment by FatOrangutan** [comment]
>In the meantime, I would maybe suggest you try out https://addons.mozilla.org/en-US/firefox/addon/tab-deduper/

That's what I'm using right now but I like your add-on better :)

Edit: I misread; I'm currently using https://addons.mozilla.org/en-US/firefox/addon/duplicate-tabs-closer/. The one that you linked is a tad too minimal for my taste :)

**Comment by tsiemens** [comment]
Right clicking on the icon now should yield a "settings" item, even on Firefox. Looked to be functioning accordingly, after a basic test.
