### ISSUE TITLE
How to ignore fragments after custom string

### ISSUE THREAD

**Issue by dolinod** [tsiemens/ChromeTabDeduper#3]
Good day,

I'd like the TabDeduper to ignore the timestamp on YouTube videos (looks like &t=XXs, where XX is a number), so that I can close duplicate YouTube tabs that are simply open at different times. It seems by default the TabDeduper does something similar with the "#" symbol that I'd like to recreate with "&t=", but I haven't been able to successfully implement this in the settings.

Could you post the correct syntax and/or include examples/tutorials of how to use the additional settings?

Thanks,

**Comment by tsiemens** [comment]
Thanks for the feedback. To get you up and running, here's something that should work:

Add this line to your "URL Transforms" in the settings menu.
```
^(.*youtube\.com/.*)&t=.*`$1
```

I'll see about adding some tips to the README soonish.

As you may have seen, there is a test panel in the settings (in orange), but if you want a bit more useful hints for other URLs, I'd strongly recommend trying out https://regex101.com/ . This is my goto for debugging regular expressions. In this case, you'll want to set the Flavor to ECMAScript, change the Delimiter (by default it is `/`) to backtick (``` ` ```), the Function from match to substitution, and move the part of the pattern after the backtick into the lower replacement value section.

**Comment by dolinod** [comment]
Thanks so much--it worked like a charm! Even without that setting, the TabDeduper did what I expected it to, but the customizability and the ability to choose which tabs to dedupe bring this particular extension to the next level! Unfortunately my own programming/coding experience is limited, but I'm sure that website and the ability to reverse engineer the line you provided will be very helpful.

Thanks again for the useful Chrome extension!
